property-level: 'auth local level'
management:
  endpoints:
    web:
      cors:
        allowed-methods: PUT,POST,GET,OPTIONS,DELETE
        allow-credentials: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boomitech?createDatabaseIfNotExist=true
    username: root
    password: skanushka
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    application:
      name: authservice
  jta:
    atomikos:
      properties:
        recovery:
          forget-orphaned-log-entries-delay:
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:12002/oauth/check_token
    client:
      client-id: web
      client-secret: pin
      access-token-uri: http://localhost:12002/oauth/token
      user-authorization-uri: http://localhost:12002/oauth/authorize
