property-level: 'auth prod level'
management:
  endpoints:
    web:
      cors:
        allowed-origins: *
        allowed-methods: *
        allowed-headers: *
        allow-credentials: true
spring:
  datasource:
    url: jdbc:mysql://sis-db.ceggfqkkv7i5.us-east-1.rds.amazonaws.com:3306/auth?createDatabaseIfNotExist=true
    username: sis_root
    password: SisTester123$
    driver-class-name: com.mysql.jdbc.Driver