property-level: 'auth dev level'
management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:8182,http://localhost:8185,http://localhost:8181
        allowed-methods: PUT,POST,GET,OPTIONS,DELETE
        allow-credentials: true
spring:
  datasource:
    url: jdbc:mysql://sis-db.ceggfqkkv7i5.us-east-1.rds.amazonaws.com:3306/auth?createDatabaseIfNotExist=true
    username: sis_root
    password: SisTester123$
    driver-class-name: com.mysql.cj.jdbc.Driver
