property-level: 'auth prod level'
management:
  endpoints:
    web:
      cors:
        allowed-methods: PUT,POST,GET,OPTIONS,DELETE
        allow-credentials: true
spring:
  datasource:
    url: jdbc:mysql://bhoomitech-dev.cyojzfaxldo6.us-east-1.rds.amazonaws.com:3306/boomitech_auth?createDatabaseIfNotExist=true
    username: bhoomitech_rw
    password: Bh00miTecH
    driver-class-name: com.mysql.cj.jdbc.Driver
  jta:
    atomikos:
      properties:
        recovery:
          forget-orphaned-log-entries-delay:
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
    client:
      client-id: web
      client-secret: pin
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
